# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate rdrand

Name:           rust-rdrand
Version:        0.8.3
Release:        1%{?dist}
Summary:        Implementation of random number generator based on rdrand and rdseed instructions

License:        ISC
URL:            https://crates.io/crates/rdrand
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

# RDRAND/RDSEED is an x86_64 CPU feature so doesn't make sense to try to build
# on other architectures.
ExclusiveArch:  x86_64

%global _description %{expand:
An implementation of random number generator based on rdrand and rdseed
instructions.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.mkd
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Sep 29 2024 Tyler Fanelli <tfanelli@redhat.com> - 0.8.3-1
- Initial package
